### ISSUE TITLE
希望 批量新标签页打开 适配Firefox身份组功能

### ISSUE THREAD

**Issue by MiunaQwQ** [lvzhenbo/115-plus#2]
希望 批量新标签页打开 适配Firefox身份组功能

目前无论在哪个身份组使用批量新标签页打开功能都只会变成默认身份组打开

**Comment by lvzhenbo** [comment]
我得调查一下，因为我没怎么用过火狐，如果油猴不支持我也没办法

**Comment by lvzhenbo** [comment]
@MiunaQwQ 请问你说的是标签分组吗

**Comment by lvzhenbo** [comment]
@MiunaQwQ https://github.com/lvzhenbo/115-plus/actions/runs/11407643907
从CI里下载脚本装一下试试，我目前只能找到这个选课可能有关

**Comment by lvzhenbo** [comment]
1.2.2版本已添加该功能，并且添加了设置开关
